# Generated by Django 4.0.4 on 2022-05-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregableApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Familia',
        ),
        migrations.AddField(
            model_name='familiares',
            name='apellido',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='familiares',
            name='edad',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='familiares',
            name='fechaDeNacimiento',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='familiares',
            name='nombre',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
