# Generated by Django 4.0.4 on 2022-06-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntregableApp', '0002_delete_familia_familiares_apellido_familiares_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BienesFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('valuacion', models.IntegerField(default=None)),
                ('antigüedad', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='SegundosFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('rol', models.CharField(default=None, max_length=50)),
                ('apellido', models.CharField(default=None, max_length=50)),
                ('fechaDeNacimiento', models.DateField(default=None)),
                ('edad', models.IntegerField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='familiares',
            name='rol',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='apellido',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='familiares',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
